<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-RI9GKG4" failures="2" tests="11" name="mem.qa.testScripts.MemSettingPageTest" time="16.363" errors="0" timestamp="2024-02-26T19:14:44 IST" skipped="0">
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkPageTitleTest" time="4.570"/>
  <system-out/>
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkPageHeadingTest" time="0.052"/>
  <system-out/>
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkShopNameTest" time="0.053"/>
  <system-out/>
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkShopURLTest" time="0.058"/>
  <system-out/>
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkShopEmailTest" time="0.057"/>
  <system-out/>
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkShopifyPlanTest" time="0.367"/>
  <system-out/>
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkSignOutBtnTest" time="0.075"/>
  <system-out/>
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkTitleGlobalPricinTest" time="0.241"/>
  <system-out/>
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkSaveBtnTest" time="3.370">
    <failure message="expected [Pricing updated successfully] but found [Something went wrong while updating the pricing rules]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Pricing updated successfully] but found [Something went wrong while updating the pricing rules]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at mem.qa.testScripts.MemSettingPageTest.checkSaveBtnTest(MemSettingPageTest.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSaveBtnTest -->
  <system-out/>
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkSaveAndUpdateTest" time="1.799">
    <failure message="expected [Pricing rules update in progress.] but found [Something went wrong while updating the pricing rules]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Pricing rules update in progress.] but found [Something went wrong while updating the pricing rules]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at mem.qa.testScripts.MemSettingPageTest.checkSaveAndUpdateTest(MemSettingPageTest.java:84)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSaveAndUpdateTest -->
  <system-out/>
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkVisibilityBtnTest" time="5.721"/>
  <system-out/>
</testsuite> <!-- mem.qa.testScripts.MemSettingPageTest -->
